---
title: "more writing"
format: html
editor: visual
---

## **Hundreds rally in favor of ban on assault weapons**

Hundreds rallied on Capitol Hill for a federal ban on assault weapons last Thursday. They came to support March Fourth-- an organization solely devoted to passing this ban.

\"I think people are choosing our right to own guns over our right to live,\" said Ivy Domont. Domont survived a mass shooting in Highland Park, a Chicago suburb, when a 21-year-old gunman used a semi-automatic rifle to kill seven people and injure 46 at a July Fourth parade. **\"**This is only a political issue in D.C.. This is a human rights issue.\" 

March Fourth started in Chicago after the July 4th shooting. The group first protested in D.C. that same July with the same mission.

Assault rifles were banned in the United States from 1994 to 2004. This year, a ban is possible again: the House of Representatives passed [H.R.1808](https://www.congress.gov/bill/117th-congress/house-bill/1808), the Assault Weapons Ban of 2022, in July. Now, the Senate will vote.

Many in the crowd were parents, children, cousins, and friends of mass shooting victims in cities including Uvalde, Las Vegas and Buffalo.

Zeneta Everhart addressed the protesters. \"Any senator voting no on this is an accomplice in the next mass shooting.\"

She told the crowd about her son, Zaire Goodman. Goodman, 20, was working at a grocery store in Buffalo, New York when an 18 year old shot him in the neck with a legally obtained AR-15. The gunman injured two more people and killed 10. Goodman survived and Everhart has advocated for this cause since then.

The leaders of March Fourth are mothers, like Everhart and Domont. 

\"The number one cause of death in children are guns,\" Domont said. Firearms kill children ages to 19 more than anything else since 2020, according to the [New England Journal of Medicine](https://www.nejm.org/doi/full/10.1056/NEJMc2201761).

Protesters want their opposition to understand: \"We don\'t want to take away the Second Amendment,\" said Nicole Lieberman, a Highland Park teacher who came to the rally. \"Just guns that are made to kill 50 people at a time. These are weapons of war.\"

Kandis Gumbs lost her cousin in Las Vegas at a music festival when a man used multiple automatic rifles to kill 60 and injure 413. Gumbs traveled across the country from Los Angeles for the rally. 

\"Our hearts are broken every time,\" she said, adding that the final straw for her was the shooting of 19 students and two teachers at Robb Elementary in Uvalde, Texas. \"It opens up that wound that is never going to close for fear those families are going through the exact same thing we are.\"

It has been four months since the shooting in Uvalde. At the rally, Angel Garza and Kimberly Rubio mourned their daughters, Amerie and Lexi. \"Do you know what it feels like to have your son come up to you and ask why his sister was shot?\" Garza asked.

Uvalde resident Gladys Gonzales also attended the rally. Her fourth-grade daughter was across the hall at Robb Elementary while an 18-year-old gunman used an automatic rifle to kill her classmates. \"If we can change one person's mind, it's been worth it,\" Gonzales said.

Gonzales doubts that the Texas government will support a federal ban. She said she hopes for compromises, like raising the age restriction to purchase guns from 18 to 21. However, Texas Gov. Greg Abbott dubbed the age limit change unconstitutional last month.

The 1994 ban\'s effectiveness is often debated during gun control conversations. In the decade after the ban, mass shootings and fatalities [increased](https://www.nytimes.com/2019/09/04/opinion/assault-weapon-ban.html), according to Stanford's John Donahue. [Opposition](https://www.washingtonpost.com/politics/2021/03/24/bidens-claim-that-1994-assault-weapons-law-brought-down-mass-shootings/) argues that the ban and violence are not related: a rising crime rate is to blame. The legislation also left multiple loopholes that may have hindered the ban\'s impact.

The Senate will vote on the ban before the end of the year. The House voted 217-213: two Republicans voted affirmatively and five Democrats voted no.

March Fourth\'s initiative will continue. 

\"We're going to go back to our states and keep going there,\" Gumbs said. \"We're not gonna let this go under the wraps.

## [go back home](https://laylanayfeh.github.io/laylanayfeh/)
