---
title: "resume"
format: html
editor: visual
---

## **Layla Nayfeh**

Washington, D.C.

laylanayfeh\@gwu.edu

508-736-7671

**Education**

**The George Washington University**

Bachelor of Arts in Journalism and Mass Communication \| Minor in Graphic Design

2019 - December 2023 \| Washington, DC

-   relevant coursework: Advanced News Writing, Sustainability and Cultural Reporting, Video Editing, Broadcast Journalism, Art of Interview, Data Analysis, Motion Graphics

**Experience**

**DCTV-** local television station

Production Intern

September 2023 - December 2023 \| Washington, DC

-   shot and edited video segments about local stories for broadcast television

**Hult Prize Foundation-** nonprofit international social entrepreneurship competition

Creative Media & Writing Intern

November 2020 - January 2022

-   served as lead editor for online content, conceptualized international digital campaigns, created online content, edited international team\'s writing and communications

**Falafel Inc-** social enterprise food brand

Online Media Director 

January 2019 - December 2021 \| Washington, DC

-   increased engagement by management of online presence for a social enterprise, generated and edited social media, marketing, photography, and impact-oriented messaging

**Acrylic Dreams-** educational nonprofit

Instructor

June 2018 - August 2019 \| Washington, DC

-   taught summer painting classes for children of refugees

**Skills & Interests**

-   graphics and video creation and editing using Adobe Photoshop, Illustrator, Premiere Pro, InDesign, After Effects, Audition

-   data analysis using Excel and R

-   proficient in Arabic

## [go back home](https://laylanayfeh.github.io/laylanayfeh/)
