---
title: "my writing"
format: html
editor: visual
---

## **D.C. organizations cope with rising food prices**

In their fight against food insecurity, D.C. organizations have had to adapt to the effects of COVID-19 and inflation during 2022.

From church-basement food pantries to activism initiatives, Washingtonians reckoned with increased hunger and steeper prices.

"Grocery prices are really hitting people's pockets," said Emily Dold, food pantry manager at the Father Mckenna Center, a D.C. organization that works to help food-insecure families. "Our number of households we serve has gone up almost double from last year and it's hard to keep up."

One-third of D.C. residents experienced food insecurity last year, according to a 2022 [Capital Area Food Bank](https://hunger-report.capitalareafoodbank.org/report-2022/) report, which found that food insecurity means ​​sometimes or often not having enough to eat.

Food insecurity declined during 2021, but shot back up last summer due to inflation, explained Karl Kever, an economist at the Bureau of Labor Statistics. 

"In the Washington area, food inflation is outpacing general inflation during some months," Kever said, adding that Lockdown and unemployment were not the sole or direct causes of it. 

"COVID had a domino effect on inflation," Kever said. "COVID aggravates elements of the economy, then people respond to that, which continues to aggravate the prices of certain goods, causing inflation."

The COVID-19 lockdown, followed by increased food prices, took a toll on charities. Food pantries like the one at the People's Congregational United Church in Ward 4 in Northwest had to scale back their services because they could not afford the food and staff that they needed.

"We've been in existence for over 40 years," said Jeanine Jackson, who manages the church food pantry. "Before the pandemic, we were serving every week. We started back up but we're only doing it once a month now."

The Father Mckenna Center also had to limit its hours for similar reasons, Dold said. Their cutbacks were compounded by a higher demand from their clients due to high food insecurity.

Jackson said that the People's Congregational United Church used to serve 100 people every Thanksgiving. This year, the number more than doubled and they expect the same turnout for Christmas, Jackson said.

Before the pandemic, the church would hold regular fundraisers to stock the pantry. Soon, Jackson said, the pantry will have to ask churchgoers and other organizations for donations to fulfill the demand.

"Food banks are not getting enough help from the government," said Martha Assefa, an anti-hunger associate at D.C. Hunger Solutions, an education and awareness initiative devoted to food insecurity. "Charities should really just supplement SNAP (food stamps)."

SNAP IS the government's anti-hunger program. Applicants must qualify for poverty to receive SNAP. The narrow qualifications exclude people in need, according to Assefa. Inflation only exacerbates this.

"The problem is that the way SNAP calculates poverty does not take inflation into account," Assefa said.

To meet the high demand, both Jackson and Dold said their pantries had to change the way they work. They partner with larger organizations, like Capital Area Food Bank, especially during the holidays to support their increased clientele. They work with more affordable grocers to source their own food.

Voting on issues like SNAP is crucial to improving food insecurity, Assefa said. D.C. Hunger Solutions spreads awareness about SNAP, not only to register people in need and to help change the legislation around it. 

Solutions are ambiguous and complicated for hungry D.C. residents and the organizations that help them.

"The hardest part is just being able to continue doing what we're doing," Jackson said.

## [go back home](https://laylanayfeh.github.io/laylanayfeh/)
